### ISSUE TITLE
Unknown template tag 'else'

### ISSUE THREAD

**Issue by Sega-Zero** [stencilproject/Stencil#276]
Reraising an issue from Sourcery repository: https://github.com/krzysztofzablocki/Sourcery/issues/735 

With the very latest release of Sourcery, my templates (that were 100% working) are now completely broken.
Can you please help me with understanding what is incorrect in my template?

**Comment by andreasley** [comment]
I've encountered the same error when a UTF8 template contained the character "[Combining Diaeresis](https://codepoints.net/U+0308)" at some point before the tag.

To be specific, my template contained `ü` encoded as 0x75 0xCC 0x88 (LATIN SMALL LETTER U + COMBINING DIAERESIS) instead of 0xC3 0xBC (LATIN SMALL LETTER U WITH DIAERESIS).
